package com.example.super_bowl_winners

fun fetchSuperBowlChampion(year: Int): Pair<String, Array<String>> {
    val index = (year - 2024) * -1
    val teamArray = arrayOf(
        "Kansas City Chiefs",
        "Kansas City Chiefs",
        "Los Angeles Rams",
        "Tampa Bay Buccaneers",
        "Kansas City Chiefs",
        "New England Patriots",
        "Philadelphia Eagles",
        "New England Patriots",
        "Denver Broncos",
        "New England Patriots",
        "Seattle Seahawks",
        "Baltimore Ravens",
        "New York Giants",
        "Green Bay Packers",
        "New Orleans Saints",
        "Pittsburgh Steelers",
        "New York Giants",
        "Indianapolis Colts",
        "Pittsburgh Steelers",
        "New England Patriots",
        "New England Patriots",
        "Tampa Bay Buccaneers",
        "New England Patriots",
        "Baltimore Ravens",
        "St. Louis Rams",
        "Denver Broncos",
        "Denver Broncos",
        "Green Bay Packers",
        "Dallas Cowboys",
        "San Francisco 49ers",
        "Dallas Cowboys",
        "Dallas Cowboys",
        "Washington",
        "New York Giants",
        "San Francisco 49ers",
        "San Francisco 49ers",
        "Washington",
        "New York Giants",
        "Chicago Bears",
        "San Francisco 49ers",
        "Los Angeles Raiders",
        "Washington",
        "San Francisco 49ers",
        "Oakland Raiders",
        "Pittsburgh Steelers",
        "Pittsburgh Steelers",
        "Dallas Cowboys",
        "Oakland Raiders",
        "Pittsburgh Steelers",
        "Pittsburgh Steelers",
        "Miami Dolphins",
        "Miami Dolphins",
        "Dallas Cowboys",
        "Baltimore Colts",
        "Kansas City Chiefs",
        "New York Jets",
        "Green Bay Packers",
        "Green Bay Packers"
    )

    val uniqueTeamArray = arrayOf(
        "Kansas City Chiefs",
        "Los Angeles Rams",
        "Tampa Bay Buccaneers",
        "New England Patriots",
        "Philadelphia Eagles",
        "Denver Broncos",
        "Seattle Seahawks",
        "Baltimore Ravens",
        "New York Giants",
        "Green Bay Packers",
        "New Orleans Saints",
        "Pittsburgh Steelers",
        "Indianapolis Colts",
        "Dallas Cowboys",
        "San Francisco 49ers",
        "Washington",
        "Chicago Bears",
        "Los Angeles Raiders",
        "Oakland Raiders",
        "Miami Dolphins",
        "Baltimore Colts",
        "New York Jets",
        "St. Louis Rams"
    )

    val randomTeamArray =
        uniqueTeamArray.filter { it != teamArray[index] }.shuffled().take(3).toTypedArray()
    val finalArray = randomTeamArray + teamArray[index]
    return Pair(teamArray[index], finalArray)
}

fun fetchNBAChampion(year: Int): Pair<String, Array<String>> {
    val index = (year - 2024) * -1
    val teamArray = arrayOf(
        "Boston Celtics",
        "Denver Nuggets",
        "Golden State Warriors",
        "Milwaukee Bucks",
        "Los Angeles Lakers",
        "Toronto Raptors",
        "Golden State Warriors",
        "Golden State Warriors",
        "Cleveland Cavaliers",
        "Golden State Warriors",
        "San Antonio Spurs",
        "Miami Heat",
        "Miami Heat",
        "Dallas Mavericks",
        "Los Angeles Lakers",
        "Los Angeles Lakers",
        "Boston Celtics",
        "San Antonio Spurs",
        "Miami Heat",
        "San Antonio Spurs",
        "Detroit Pistons",
        "San Antonio Spurs",
        "Los Angeles Lakers",
        "Los Angeles Lakers",
        "Los Angeles Lakers",
        "San Antonio Spurs",
        "Chicago Bulls",
        "Chicago Bulls",
        "Chicago Bulls",
        "Houston Rockets",
        "Houston Rockets",
        "Chicago Bulls",
        "Chicago Bulls",
        "Chicago Bulls",
        "Detroit Pistons",
        "Detroit Pistons",
        "Los Angeles Lakers",
        "Los Angeles Lakers",
        "Boston Celtics",
        "Los Angeles Lakers",
        "Boston Celtics",
        "Philadelphia 76ers",
        "Los Angeles Lakers",
        "Boston Celtics",
        "Los Angeles Lakers",
        "Seattle SuperSonics",
        "Washington Bullets",
        "Portland Trail Blazers"
    )

    val uniqueNbaTeamArray = arrayOf(
        "Boston Celtics",
        "Denver Nuggets",
        "Golden State Warriors",
        "Milwaukee Bucks",
        "Los Angeles Lakers",
        "Toronto Raptors",
        "Cleveland Cavaliers",
        "San Antonio Spurs",
        "Miami Heat",
        "Dallas Mavericks",
        "Detroit Pistons",
        "Chicago Bulls",
        "Houston Rockets",
        "Philadelphia 76ers",
        "Seattle SuperSonics",
        "Washington Bullets",
        "Portland Trail Blazers"
    )

    val randomNbaTeamArray =
        uniqueNbaTeamArray.filter { it != teamArray[index] }.shuffled().take(3).toTypedArray()
    val finalArray = randomNbaTeamArray + teamArray[index]
    return Pair(teamArray[index], finalArray)
}